# fly.toml app configuration file generated for bskypost on 2023-12-08T22:24:40-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bskypost"
primary_region = "ewr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"